export const CONSTANTS = {
    LIVE_TRACKING_THRESHOLD_MS: 30 * 60 * 1000,
    TRACKING_POLL_INTERVAL_MS: 30000,
    LOW_STOCK_THRESHOLD_DEFAULT: 10,
    GRID_ROWS_DEFAULT: 5,
    GRID_COLS_DEFAULT: 10,
};
